server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      default-zone: http://localhost:8761/eureka
  instance: 
    hostname: localhost
    
spring: 
  cloud:
    gateway:
      discovery:
        locator: 
          enabled: true
      routes:
        - id: user-microservice
          uri: lb://user-microservice
          predicates: 
            - Path= /user/**   
          filter:
            - AuthFilter   
        - id: cars-microservice
          uri: lb://cars-microservice
          predicates: 
            - Path= /car/** 
          filter:
            - AuthFilter         
        - id: bike-microservice
          uri: lb://bike-microservice
          predicates: 
            - Path= /bike/**
          filter:
            - AuthFilter   
        - id: auth-service
          uri: lb://auth-service
          predicates: 
            - Path= /auth/**
          filter:
            - AuthFilter   
        
