server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: auth-jwt
          uri: https://github.com/jhonAp25/microservices-test
          search-paths: config-data
  application:
    name: configServer



